# Assignment 3

In [15]:
def divide(a,b):
    try:
        c=a/b
    except Exception:
        print("Hi!,you cannot divide by zero")
    else:
        print(c)
    finally:
        print("please try with number > than 0")
divide(2,0)

Hi!,you cannot divide by zero
please try with number > than 0


In [3]:
subjects=["Americans", "Indians"]
verbs=["Play", "watch"]
objects=["Baseball","cricket"]
sentence=[]
for a in subjects:
    for b in verbs:
        for c in objects:
            sentence.append(a+" "+b+" "+c)
for i in sentence:
    print(i)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [19]:
import numpy as np
def raj(list):
    x=np.array(list)
    p=[]
    for i in range(0,len(x)):
        for item in x:
            p.append(item**i)
    return np.reshape(p,(4,4))


In [22]:
print(raj(list=[4,8,12,16]))

[[   1    1    1    1]
 [   4    8   12   16]
 [  16   64  144  256]
 [  64  512 1728 4096]]
